<?php
/**
 * Created by PhpStorm.
 * User: cronfy
 * Date: 22.08.18
 * Time: 16:38
 */

namespace cronfy\geoname\console\controllers;


use cronfy\geoname\BaseModule;

/**
 * @property BaseModule $module
 */
class MigrateController extends \yii\console\controllers\MigrateController
{
    public function init()
    {
        $this->db = $this->module->getSqliteDatabase();
        $migrationsPath = dirname($this->module->basePath) . '/common/migrations/sqlite';
        $this->migrationPath = [
            $migrationsPath,
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}